# Generated by Django 5.2.16 on 2026-07-13 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_uz', models.TextField(blank=True, verbose_name="Umumiy ma'lumot (uz)")),
                ('overview_ru', models.TextField(blank=True, verbose_name="Umumiy ma'lumot (ru)")),
                ('overview_en', models.TextField(blank=True, verbose_name="Umumiy ma'lumot (en)")),
                ('issn_print', models.CharField(blank=True, max_length=20, verbose_name='ISSN (Print)')),
                ('issn_online', models.CharField(blank=True, max_length=20, verbose_name='ISSN (Online)')),
                ('indexed_in', models.TextField(blank=True, help_text='Har bir bazani yangi qatorga yozing (Google Scholar, Scopus, ...).', verbose_name='Indekslangan bazalar')),
                ('submit_url', models.URLField(blank=True, verbose_name='Maqola yuborish havolasi')),
                ('is_open_access_journal', models.BooleanField(default=True, verbose_name='Ochiq kirishli jurnal')),
            ],
            options={
                'verbose_name': "Jurnal ma'lumoti",
                'verbose_name_plural': "Jurnal ma'lumoti",
            },
        ),
        migrations.CreateModel(
            name='JournalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name="Ko'rsatkich nomi (uz)")),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name="Ko'rsatkich nomi (ru)")),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name="Ko'rsatkich nomi (en)")),
                ('value', models.CharField(max_length=50, verbose_name='Qiymat')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yil')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Jurnal ko'rsatkichi",
                'verbose_name_plural': "Jurnal ko'rsatkichlari",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JournalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Sarlavha (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (ru)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (en)')),
                ('slug', models.SlugField(blank=True, max_length=420, unique=True, verbose_name='Slug')),
                ('content_uz', models.TextField(blank=True, verbose_name='Matn (uz)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Matn (ru)')),
                ('content_en', models.TextField(blank=True, verbose_name='Matn (en)')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='updates/', verbose_name='Banner rasm')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Nashr sanasi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
            ],
            options={
                'verbose_name': 'Jurnal yangiligi',
                'verbose_name_plural': 'Jurnal yangiliklari',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Obuna sanasi')),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachilar (alerts)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('research', 'Original tadqiqot'), ('review', 'Sharh maqola'), ('case_report', 'Klinik kuzatuv'), ('editorial', 'Muharrir maqolasi'), ('clinical_trial', 'Klinik sinov'), ('other', 'Boshqa')], default='research', max_length=20, verbose_name='Maqola turi'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_open_access',
            field=models.BooleanField(default=True, verbose_name='Ochiq kirish'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbs/', verbose_name='Kichik rasm'),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='is_editor_in_chief',
            field=models.BooleanField(default=False, verbose_name='Bosh muharrir'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=400, verbose_name='Sarlavha (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (ru)')),
                ('title_en', models.CharField(blank=True, max_length=400, verbose_name='Sarlavha (en)')),
                ('slug', models.SlugField(blank=True, max_length=420, unique=True, verbose_name='Slug')),
                ('description_uz', models.TextField(blank=True, verbose_name='Tavsif (uz)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (ru)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (en)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Rasm')),
                ('status', models.CharField(choices=[('open', 'Qabul ochiq'), ('closed', 'Yopiq')], default='open', max_length=10, verbose_name='Holat')),
                ('submission_deadline', models.DateField(blank=True, null=True, verbose_name='Topshirish muddati')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('related_articles', models.ManyToManyField(blank=True, related_name='collections', to='journal.article', verbose_name="Bog'liq maqolalar")),
            ],
            options={
                'verbose_name': "To'plam / Call for papers",
                'verbose_name_plural': "To'plamlar / Call for papers",
                'ordering': ['order', '-submission_deadline'],
            },
        ),
    ]
