# Generated by Django 5.2.16 on 2026-07-13 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalinfo_journalmetric_journalupdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_articles', to=settings.AUTH_USER_MODEL, verbose_name='Topshirgan foydalanuvchi'),
        ),
    ]
