# Generated by Django 5.2.16 on 2026-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_author_academic_degree_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Admin tomonidan rad etilganda yoziladi.', verbose_name='Rad etish sababi'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('rejected', 'Rad etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=12, verbose_name='Holat'),
        ),
    ]
