# Generated by Django 5.2.16 on 2026-07-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_article_rejection_reason_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('review', "Ko'rib chiqilmoqda"), ('published', 'Chop etilgan'), ('rejected', 'Rad etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=12, verbose_name='Holat'),
        ),
    ]
