# Generated by Django 5.2.16 on 2026-07-15 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='conflict_of_interest_en',
            field=models.TextField(blank=True, verbose_name="Manfaatlar to'qnashuvi (en)"),
        ),
        migrations.AddField(
            model_name='article',
            name='conflict_of_interest_ru',
            field=models.TextField(blank=True, verbose_name="Manfaatlar to'qnashuvi (ru)"),
        ),
        migrations.AddField(
            model_name='article',
            name='conflict_of_interest_uz',
            field=models.TextField(blank=True, verbose_name="Manfaatlar to'qnashuvi (uz)"),
        ),
        migrations.AddField(
            model_name='article',
            name='corresponding_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corresponding_articles', to='journal.author', verbose_name="Mas'ul muallif"),
        ),
        migrations.AddField(
            model_name='article',
            name='ethics_statement_en',
            field=models.TextField(blank=True, verbose_name='Etika bayonoti (en)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ethics_statement_ru',
            field=models.TextField(blank=True, verbose_name='Etika bayonoti (ru)'),
        ),
        migrations.AddField(
            model_name='article',
            name='ethics_statement_uz',
            field=models.TextField(blank=True, verbose_name='Etika bayonoti (uz)'),
        ),
        migrations.AddField(
            model_name='article',
            name='full_text_en',
            field=models.TextField(blank=True, verbose_name="To'liq matn (en)"),
        ),
        migrations.AddField(
            model_name='article',
            name='full_text_ru',
            field=models.TextField(blank=True, verbose_name="To'liq matn (ru)"),
        ),
        migrations.AddField(
            model_name='article',
            name='full_text_uz',
            field=models.TextField(blank=True, verbose_name="To'liq matn (uz)"),
        ),
        migrations.AddField(
            model_name='article',
            name='funding_statement_en',
            field=models.TextField(blank=True, verbose_name='Moliyalashtirish (en)'),
        ),
        migrations.AddField(
            model_name='article',
            name='funding_statement_ru',
            field=models.TextField(blank=True, verbose_name='Moliyalashtirish (ru)'),
        ),
        migrations.AddField(
            model_name='article',
            name='funding_statement_uz',
            field=models.TextField(blank=True, verbose_name='Moliyalashtirish (uz)'),
        ),
        migrations.CreateModel(
            name='ArticleFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='articles/figures/%Y/%m/', verbose_name='Rasm')),
                ('caption_uz', models.CharField(blank=True, max_length=500, verbose_name='Tagyozuv (uz)')),
                ('caption_ru', models.CharField(blank=True, max_length=500, verbose_name='Tagyozuv (ru)')),
                ('caption_en', models.CharField(blank=True, max_length=500, verbose_name='Tagyozuv (en)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='journal.article', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Maqola rasmi',
                'verbose_name_plural': 'Maqola rasmlari',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleSupplementaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='articles/supplementary/%Y/%m/', verbose_name='Fayl')),
                ('title_uz', models.CharField(max_length=300, verbose_name='Nomi (uz)')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Nomi (ru)')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='Nomi (en)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_files', to='journal.article', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': "Qo'shimcha material",
                'verbose_name_plural': "Qo'shimcha materiallar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('citation_text', models.TextField(help_text="To'liq: muallif(lar), sarlavha, jurnal, yil, sahifalar.", verbose_name='Iqtibos matni')),
                ('doi_or_url', models.CharField(blank=True, max_length=300, verbose_name='DOI yoki havola')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='journal.article', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Adabiyot',
                'verbose_name_plural': "Adabiyotlar ro'yxati",
                'ordering': ['order', 'id'],
            },
        ),
    ]
