# Generated by Django 5.2.16 on 2026-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_article_conflict_of_interest_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirm_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tasdiqlash tokeni'),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Tasdiqlangan'),
        ),
    ]
