# Generated by Django 5.2.16 on 2026-07-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_newslettersubscription_confirm_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('decision', models.CharField(choices=[('accept', 'Qabul qilish'), ('revise', 'Qayta ishlash'), ('reject', 'Rad etish'), ('pending', 'Kutilmoqda')], default='pending', max_length=20, verbose_name='Xulosa')),
                ('comments_for_author', models.TextField(blank=True, verbose_name='Muallif uchun izohlar')),
                ('comments_for_editor', models.TextField(blank=True, verbose_name='Muharrir uchun xufyona izohlar')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='journal.article', verbose_name='Maqola')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Taqrizchi')),
            ],
            options={
                'verbose_name': 'Taqriz',
                'verbose_name_plural': 'Taqrizlar',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'reviewer')},
            },
        ),
    ]
