# Generated by Django 5.2.16 on 2026-08-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialboardmember',
            name='is_editor_in_chief',
        ),
        migrations.AddField(
            model_name='article',
            name='ai_disclosure',
            field=models.TextField(blank=True, help_text='Tadqiqotda AI dan qanday foydalanilganligi.', verbose_name="Sun'iy intellekt deklaratsiyasi"),
        ),
        migrations.AddField(
            model_name='article',
            name='plagiarism_score',
            field=models.PositiveIntegerField(blank=True, help_text='iThenticate plagiat tekshiruvi natijasi.', null=True, verbose_name='Plagiat foizi (%)'),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='role',
            field=models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('associate_editor', "Bosh muharrir o'rinbosari"), ('section_editor', "Bo'lim muharriri"), ('member', "Hay'at a'zosi"), ('secretary', 'Tahririyat kotibi')], default='member', max_length=30, verbose_name="Lavozim (Nizom bo'yicha)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('research', 'Original tadqiqot'), ('systematic_review', 'Tizimli sharhlar'), ('case_report', 'Klinik holat'), ('short_communication', 'Qisqa xabar'), ('review', 'Sharh maqola'), ('clinical_guideline', "Klinik ko'rsatmalar"), ('perspective', 'Perspektiva'), ('letter', 'Muharrirga xat'), ('other', 'Boshqa')], default='research', max_length=20, verbose_name='Maqola turi'),
        ),
    ]
