# Generated by Django 5.2.16 on 2026-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_remove_editorialboardmember_is_editor_in_chief_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ismingiz')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzilingiz')),
                ('title', models.CharField(max_length=255, verbose_name='Taklif mavzusi')),
                ('description', models.TextField(verbose_name='Batafsil matn')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('in_progress', 'Jarayonda'), ('completed', 'Bajarildi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Sayt taklifi',
                'verbose_name_plural': 'Sayt takliflari',
                'ordering': ['-created_at'],
            },
        ),
    ]
