RU_DICT = {
    'Adabiyot': 'Литература',
    'Admin tomonidan rad etilganda yoziladi.': 'Заполняется при отклонении администратором.',
    'Afisha': 'Афиша',
    'Arxivlangan': 'В архиве',
    'Asosiy sayt Doctor ID (ixtiyoriy)': 'ID доктора основного сайта (необязательно)',
    'Aspirantura': 'Аспирантура',
    'Aspirantura/Ordinatura dasturi': 'Программа аспирантуры/ординатуры',
    'Aspirantura/Ordinatura': 'Аспирантура/Ординатура',
    'Banner rasm': 'Баннерное изображение',
    'Biografiya (en)': 'Биография (англ)',
    'Biografiya (ru)': 'Биография (рус)',
    'Biografiya (uz)': 'Биография (узб)',
    'Bosh muharrir': 'Главный редактор',
    'Boshlanish sanasi': 'Дата начала',
    'Boshqa': 'Другое',
    'Chop etilgan': 'Опубликовано',
    'DOI yoki havola': 'DOI или ссылка',
    'DOI': 'DOI',
    'Dastur (PDF)': 'Программа (PDF)',
    'Email': 'Email',
    'Etika bayonoti (en)': 'Заявление об этике (англ)',
    'Etika bayonoti (ru)': 'Заявление об этике (рус)',
    'Etika bayonoti (uz)': 'Заявление об этике (узб)',
    'Faol': 'Активный',
    'Fayl': 'Файл',
    'Foydalanuvchi': 'Пользователь',
    'Grant': 'Грант',
    'Grantlar': 'Гранты',
    'Har bir bazani yangi qatorga yozing (Google Scholar, Scopus, ...).': 'Укажите каждую базу данных с новой строки (Google Scholar, Scopus, ...).',
    'Holat': 'Статус',
    'ISSN (Online)': 'ISSN (Online)',
    'ISSN (Print)': 'ISSN (Print)',
    'Ilmiy kengash': 'Ученый совет',
    'Indekslangan bazalar': 'Индексированные базы',
    'Iqtibos matni': 'Текст цитаты',
    'Iqtiboslar soni': 'Количество цитирований',
    'Ish joyi/lavozimi (en)': 'Место работы/должность (англ)',
    'Ish joyi/lavozimi (ru)': 'Место работы/должность (рус)',
    'Ish joyi/lavozimi (uz)': 'Место работы/должность (узб)',
    'Jurnal soni': 'Выпуск журнала',
    'Jurnal sonlari': 'Выпуски журнала',
    'Jurnal yangiligi': 'Новость журнала',
    'Jurnal yangiliklari': 'Новости журнала',
    'Kafedra mudiri': 'Заведующий кафедрой',
    'Kafedra': 'Кафедра',
    'Kafedralar': 'Кафедры',
    'Kalit': 'Ключ',
    'Kelajakda REST API orqali sinxronlash uchun tashqi ID.': 'Внешний ID для синхронизации через REST API в будущем.',
    'Kichik rasm': 'Миниатюра',
    'Klinik kuzatuv': 'Клиническое наблюдение',
    'Klinik sinov': 'Клиническое испытание',
    'Konferensiya': 'Конференция',
    'Konferensiyalar': 'Конференции',
    'Kutilmoqda': 'В ожидании',
    'Lavozim (en)': 'Должность (англ)',
    'Lavozim (ru)': 'Должность (рус)',
    'Lavozim (uz)': 'Должность (узб)',
    'Loyiha rahbarlari': 'Руководители проекта',
    'Manzil (en)': 'Адрес (англ)',
    'Manzil (ru)': 'Адрес (рус)',
    'Manzil (uz)': 'Адрес (узб)',
    'Maqola rasmi': 'Изображение статьи',
    'Maqola rasmlari': 'Изображения статьи',
    'Maqola turi': 'Тип статьи',
    'Maqola yuborish havolasi': 'Ссылка для отправки статьи',
    'Maqola': 'Статья',
    'Maqolalar': 'Статьи',
    'Matn (en)': 'Текст (англ)',
    'Matn (ru)': 'Текст (рус)',
    'Matn (uz)': 'Текст (узб)',
    'Moliyalashtirish (en)': 'Финансирование (англ)',
    'Moliyalashtirish (ru)': 'Финансирование (рус)',
    'Moliyalashtirish (uz)': 'Финансирование (узб)',
    'Moliyalashtiruvchi': 'Спонсор',
    'Muallif uchun izohlar': 'Комментарии для автора',
    'Muallif': 'Автор',
    'Mualliflar': 'Авторы',
    'Muddat': 'Срок',
    'Muharrir maqolasi': 'Редакционная статья',
    'Muharrir uchun xufyona izohlar': 'Конфиденциальные комментарии для редактора',
    'Muqova': 'Обложка',
    'Nashr sanasi': 'Дата публикации',
    'Nomi (en)': 'Название (англ)',
    'Nomi (ru)': 'Название (рус)',
    'Nomi (uz)': 'Название (узб)',
    'Number (son)': 'Номер',
    'Obuna sanasi': 'Дата подписки',
    'Obunachi': 'Подписчик',
    'Obunachilar (alerts)': 'Подписчики (оповещения)',
    'Ochiq kirish': 'Открытый доступ',
    'Ochiq kirishli jurnal': 'Журнал открытого доступа',
    'Ordinatura': 'Ординатура',
    'Original tadqiqot': 'Оригинальное исследование',
    'PDF fayl': 'PDF файл',
    'Qabul ochiq': 'Прием открыт',
    'Qabul qilish': 'Принять',
    'Qayta ishlash': 'На доработку',
    'Qiymat': 'Значение',
    'Qoralama': 'Черновик',
    'Rad etilgan': 'Отклонено',
    'Rad etish sababi': 'Причина отклонения',
    'Rad etish': 'Отклонить',
    'Rasm': 'Изображение',
    'Sahifalar': 'Страницы',
    'Sharh maqola': 'Обзорная статья',
    'Slug': 'Slug (ЧПУ)',
    'Statik sahifa': 'Статическая страница',
    'Statik sahifalar': 'Статические страницы',
    'Tagyozuv (en)': 'Подпись (англ)',
    'Tagyozuv (ru)': 'Подпись (рус)',
    'Tagyozuv (uz)': 'Подпись (узб)',
    'Talablar (PDF)': 'Требования (PDF)',
    'Taqriz': 'Рецензия',
    'Taqrizchi': 'Рецензент',
    'Taqrizlar': 'Рецензии',
    'Tartib raqami': 'Порядковый номер',
    'Tartib': 'Порядок',
    'Tasdiqlangan': 'Подтвержден',
    'Tasdiqlash tokeni': 'Токен подтверждения',
    'Tavsif (en)': 'Описание (англ)',
    'Tavsif (ru)': 'Описание (рус)',
    'Tavsif (uz)': 'Описание (узб)',
    'Topshirgan foydalanuvchi': 'Пользователь, подавший заявку',
    'Topshirish muddati': 'Срок сдачи',
    'Tugash sanasi': 'Дата окончания',
    'Turi': 'Тип',
    'Volume (tom)': 'Том',
    'Xulosa': 'Заключение',
    'Yakunlangan': 'Завершено',
    'Yangilangan': 'Обновлено',
    'Yaratilgan': 'Создано',
    'Yil': 'Год',
    'Yopiq': 'Закрыто',
}

EN_DICT = {
    'Adabiyot': 'Reference',
    'Admin tomonidan rad etilganda yoziladi.': 'Filled in when rejected by admin.',
    'Afisha': 'Poster',
    'Arxivlangan': 'Archived',
    'Asosiy sayt Doctor ID (ixtiyoriy)': 'Main site Doctor ID (optional)',
    'Aspirantura': 'Postgraduate',
    'Aspirantura/Ordinatura dasturi': 'Postgraduate/Residency program',
    'Aspirantura/Ordinatura': 'Postgraduate/Residency',
    'Banner rasm': 'Banner image',
    'Biografiya (en)': 'Biography (en)',
    'Biografiya (ru)': 'Biography (ru)',
    'Biografiya (uz)': 'Biography (uz)',
    'Bosh muharrir': 'Editor-in-Chief',
    'Boshlanish sanasi': 'Start date',
    'Boshqa': 'Other',
    'Chop etilgan': 'Published',
    'DOI yoki havola': 'DOI or link',
    'DOI': 'DOI',
    'Dastur (PDF)': 'Program (PDF)',
    'Email': 'Email',
    'Etika bayonoti (en)': 'Ethics statement (en)',
    'Etika bayonoti (ru)': 'Ethics statement (ru)',
    'Etika bayonoti (uz)': 'Ethics statement (uz)',
    'Faol': 'Active',
    'Fayl': 'File',
    'Foydalanuvchi': 'User',
    'Grant': 'Grant',
    'Grantlar': 'Grants',
    'Har bir bazani yangi qatorga yozing (Google Scholar, Scopus, ...).': 'Enter each database on a new line (Google Scholar, Scopus, ...).',
    'Holat': 'Status',
    'ISSN (Online)': 'ISSN (Online)',
    'ISSN (Print)': 'ISSN (Print)',
    'Ilmiy kengash': 'Scientific Council',
    'Indekslangan bazalar': 'Indexed databases',
    'Iqtibos matni': 'Citation text',
    'Iqtiboslar soni': 'Number of citations',
    'Ish joyi/lavozimi (en)': 'Affiliation/position (en)',
    'Ish joyi/lavozimi (ru)': 'Affiliation/position (ru)',
    'Ish joyi/lavozimi (uz)': 'Affiliation/position (uz)',
    'Jurnal soni': 'Journal issue',
    'Jurnal sonlari': 'Journal issues',
    'Jurnal yangiligi': 'Journal news',
    'Jurnal yangiliklari': 'Journal news',
    'Kafedra mudiri': 'Head of Department',
    'Kafedra': 'Department',
    'Kafedralar': 'Departments',
    'Kalit': 'Key',
    'Kelajakda REST API orqali sinxronlash uchun tashqi ID.': 'External ID for synchronization via REST API in the future.',
    'Kichik rasm': 'Thumbnail',
    'Klinik kuzatuv': 'Clinical observation',
    'Klinik sinov': 'Clinical trial',
    'Konferensiya': 'Conference',
    'Konferensiyalar': 'Conferences',
    'Kutilmoqda': 'Pending',
    'Lavozim (en)': 'Position (en)',
    'Lavozim (ru)': 'Position (ru)',
    'Lavozim (uz)': 'Position (uz)',
    'Loyiha rahbarlari': 'Project leaders',
    'Manzil (en)': 'Address (en)',
    'Manzil (ru)': 'Address (ru)',
    'Manzil (uz)': 'Address (uz)',
    'Maqola rasmi': 'Article image',
    'Maqola rasmlari': 'Article images',
    'Maqola turi': 'Article type',
    'Maqola yuborish havolasi': 'Article submission link',
    'Maqola': 'Article',
    'Maqolalar': 'Articles',
    'Matn (en)': 'Text (en)',
    'Matn (ru)': 'Text (ru)',
    'Matn (uz)': 'Text (uz)',
    'Moliyalashtirish (en)': 'Funding (en)',
    'Moliyalashtirish (ru)': 'Funding (ru)',
    'Moliyalashtirish (uz)': 'Funding (uz)',
    'Moliyalashtiruvchi': 'Sponsor',
    'Muallif uchun izohlar': 'Comments for the author',
    'Muallif': 'Author',
    'Mualliflar': 'Authors',
    'Muddat': 'Term',
    'Muharrir maqolasi': 'Editorial',
    'Muharrir uchun xufyona izohlar': 'Confidential comments for the editor',
    'Muqova': 'Cover',
    'Nashr sanasi': 'Publication date',
    'Nomi (en)': 'Name (en)',
    'Nomi (ru)': 'Name (ru)',
    'Nomi (uz)': 'Name (uz)',
    'Number (son)': 'Number',
    'Obuna sanasi': 'Subscription date',
    'Obunachi': 'Subscriber',
    'Obunachilar (alerts)': 'Subscribers (alerts)',
    'Ochiq kirish': 'Open access',
    'Ochiq kirishli jurnal': 'Open access journal',
    'Ordinatura': 'Residency',
    'Original tadqiqot': 'Original research',
    'PDF fayl': 'PDF file',
    'Qabul ochiq': 'Admission open',
    'Qabul qilish': 'Accept',
    'Qayta ishlash': 'Revise',
    'Qiymat': 'Value',
    'Qoralama': 'Draft',
    'Rad etilgan': 'Rejected',
    'Rad etish sababi': 'Reason for rejection',
    'Rad etish': 'Reject',
    'Rasm': 'Image',
    'Sahifalar': 'Pages',
    'Sharh maqola': 'Review article',
    'Slug': 'Slug',
    'Statik sahifa': 'Static page',
    'Statik sahifalar': 'Static pages',
    'Tagyozuv (en)': 'Caption (en)',
    'Tagyozuv (ru)': 'Caption (ru)',
    'Tagyozuv (uz)': 'Caption (uz)',
    'Talablar (PDF)': 'Requirements (PDF)',
    'Taqriz': 'Review',
    'Taqrizchi': 'Reviewer',
    'Taqrizlar': 'Reviews',
    'Tartib raqami': 'Sequence number',
    'Tartib': 'Order',
    'Tasdiqlangan': 'Confirmed',
    'Tasdiqlash tokeni': 'Confirmation token',
    'Tavsif (en)': 'Description (en)',
    'Tavsif (ru)': 'Description (ru)',
    'Tavsif (uz)': 'Description (uz)',
    'Topshirgan foydalanuvchi': 'Submitted user',
    'Topshirish muddati': 'Submission deadline',
    'Tugash sanasi': 'End date',
    'Turi': 'Type',
    'Volume (tom)': 'Volume',
    'Xulosa': 'Conclusion',
    'Yakunlangan': 'Completed',
    'Yangilangan': 'Updated',
    'Yaratilgan': 'Created',
    'Yil': 'Year',
    'Yopiq': 'Closed',
}

import re
with open('compile_translations.py', 'r', encoding='utf-8') as f:
    content = f.read()

ru_match = re.search(r'RU\s*=\s*\{', content)
if ru_match:
    idx = ru_match.end()
    ru_str = ''
    for k, v in RU_DICT.items():
        ru_str += f"    {repr(k)}: {repr(v)},\n"
    content = content[:idx] + '\n' + ru_str + content[idx:]

en_match = re.search(r'EN\s*=\s*\{', content)
if en_match:
    idx = en_match.end()
    en_str = ''
    for k, v in EN_DICT.items():
        en_str += f"    {repr(k)}: {repr(v)},\n"
    content = content[:idx] + '\n' + en_str + content[idx:]

with open('compile_translations.py', 'w', encoding='utf-8') as f:
    f.write(content)
print('Updated translations')
