import datetime

from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.test import TestCase
from django.urls import reverse
from django.utils import translation

from .models import (
    Article,
    Author,
    Category,
    Collection,
    Conference,
    JournalUpdate,
    NewsletterSubscription,
)


class ModelTests(TestCase):
    def test_slug_autogenerated_and_unique(self):
        a1 = Article.objects.create(title_uz='Bir xil sarlavha', title_en='Same Title')
        a2 = Article.objects.create(title_uz='Bir xil sarlavha', title_en='Same Title')
        self.assertEqual(a1.slug, 'same-title')
        self.assertEqual(a2.slug, 'same-title-2')

    def test_author_slug_from_full_name(self):
        author = Author.objects.create(full_name='Alisher Karimov')
        self.assertEqual(author.slug, 'alisher-karimov')

    def test_translated_property_fallback_to_uz(self):
        cat = Category.objects.create(name_uz='Onkologiya')
        with translation.override('en'):
            # No English value -> falls back to Uzbek.
            self.assertEqual(cat.name, 'Onkologiya')

    def test_translated_property_active_language(self):
        cat = Category.objects.create(name_uz='Onkologiya', name_en='Oncology')
        with translation.override('en'):
            self.assertEqual(cat.name, 'Oncology')
        with translation.override('uz'):
            self.assertEqual(cat.name, 'Onkologiya')

    def test_citation_apa_contains_authors_and_doi(self):
        a = Article.objects.create(
            title_uz='Test', title_en='Test',
            publication_date=datetime.date(2025, 1, 1), doi='10.1/x',
        )
        a.authors.add(Author.objects.create(full_name='A One'),
                      Author.objects.create(full_name='B Two'))
        cite = a.citation_apa()
        self.assertIn('(2025)', cite)
        self.assertIn('doi.org/10.1/x', cite)

    def test_conference_is_upcoming(self):
        today = datetime.date.today()
        future = Conference.objects.create(title_uz='F', date_start=today + datetime.timedelta(days=5))
        past = Conference.objects.create(title_uz='P', date_start=today - datetime.timedelta(days=5))
        self.assertTrue(future.is_upcoming)
        self.assertFalse(past.is_upcoming)


class ViewTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.cat = Category.objects.create(name_uz='Onkojarrohlik', slug='onkojarrohlik')
        cls.author = Author.objects.create(full_name='Alisher Karimov')
        cls.published = Article.objects.create(
            title_uz='Oshqozon saratoni', title_en='Gastric cancer',
            status=Article.Status.PUBLISHED, category=cls.cat,
            publication_date=datetime.date(2025, 3, 1), abstract_uz='Annotatsiya matni',
        )
        cls.published.authors.add(cls.author)
        cls.draft = Article.objects.create(
            title_uz='Qoralama', title_en='Draft', status=Article.Status.DRAFT,
        )

    def test_home_ok(self):
        r = self.client.get(reverse('journal:home'))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, 'Oshqozon saratoni')

    def test_article_list_excludes_drafts(self):
        r = self.client.get(reverse('journal:article_list'))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, 'Oshqozon saratoni')
        self.assertNotContains(r, 'Qoralama')

    def test_article_list_search(self):
        r = self.client.get(reverse('journal:article_list'), {'q': 'oshqozon'})
        self.assertContains(r, 'Oshqozon saratoni')
        r2 = self.client.get(reverse('journal:article_list'), {'q': 'nonexistentxyz'})
        self.assertNotContains(r2, 'Oshqozon saratoni')

    def test_article_list_filter_by_category(self):
        r = self.client.get(reverse('journal:article_list'), {'category': 'onkojarrohlik'})
        self.assertContains(r, 'Oshqozon saratoni')

    def test_article_detail_increments_views(self):
        self.assertEqual(self.published.views_count, 0)
        self.client.get(self.published.get_absolute_url())
        self.published.refresh_from_db()
        self.assertEqual(self.published.views_count, 1)

    def test_draft_detail_404_for_anonymous(self):
        r = self.client.get(self.draft.get_absolute_url())
        self.assertEqual(r.status_code, 404)

    def test_author_detail_ok(self):
        r = self.client.get(self.author.get_absolute_url())
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, 'Alisher Karimov')

    def test_root_redirects_to_journal(self):
        r = self.client.get('/')
        self.assertRedirects(r, '/ilm-fan/', status_code=302, target_status_code=200)


class APITests(TestCase):
    @classmethod
    def setUpTestData(cls):
        cls.article = Article.objects.create(
            title_uz='API maqola', title_en='API article',
            status=Article.Status.PUBLISHED, publication_date=datetime.date(2025, 2, 1),
        )
        Article.objects.create(title_uz='Yashirin', title_en='Hidden', status=Article.Status.DRAFT)

    def test_api_lists_only_published(self):
        r = self.client.get('/api/articles/')
        self.assertEqual(r.status_code, 200)
        data = r.json()
        titles = [a['title'] for a in data['results']]
        self.assertIn('API maqola', titles)
        self.assertNotIn('Yashirin', titles)

    def test_api_detail_has_citation(self):
        r = self.client.get(f'/api/articles/{self.article.slug}/')
        self.assertEqual(r.status_code, 200)
        self.assertIn('citation_apa', r.json())

    def test_api_read_only(self):
        r = self.client.post('/api/articles/', {'title_uz': 'x'})
        self.assertIn(r.status_code, (401, 403, 405))


class NewFeaturesTests(TestCase):
    def test_newsletter_subscribe_saves_email(self):
        r = self.client.post(reverse('journal:newsletter_subscribe'),
                             {'email': 'reader@example.com', 'next': '/ilm-fan/'})
        self.assertEqual(r.status_code, 302)
        self.assertTrue(NewsletterSubscription.objects.filter(email='reader@example.com').exists())

    def test_newsletter_rejects_invalid_email(self):
        self.client.post(reverse('journal:newsletter_subscribe'), {'email': 'not-an-email'})
        self.assertEqual(NewsletterSubscription.objects.count(), 0)

    def test_newsletter_get_not_allowed(self):
        r = self.client.get(reverse('journal:newsletter_subscribe'))
        self.assertEqual(r.status_code, 405)

    def test_update_pages(self):
        u = JournalUpdate.objects.create(title_uz='Yangilik', title_en='Update', content_uz='Matn')
        self.assertEqual(self.client.get(reverse('journal:update_list')).status_code, 200)
        self.assertEqual(self.client.get(u.get_absolute_url()).status_code, 200)

    def test_collection_pages(self):
        c = Collection.objects.create(title_uz='Toplam', title_en='Collection')
        self.assertEqual(self.client.get(reverse('journal:collection_list')).status_code, 200)
        self.assertEqual(self.client.get(c.get_absolute_url()).status_code, 200)

    def test_article_type_display_default(self):
        a = Article.objects.create(title_uz='T', title_en='T')
        self.assertEqual(a.article_type, Article.ArticleType.RESEARCH)
        self.assertTrue(a.is_open_access)


class AuthAndSubmissionTests(TestCase):
    def setUp(self):
        self.cat = Category.objects.create(name_uz='Onkojarrohlik', name_en='Surgical Oncology', slug='surg')

    def test_register_creates_user_and_logs_in(self):
        r = self.client.post(reverse('journal:register'), {
            'username': 'testauthor',
            'password1': 'Str0ngP@ss!',
            'password2': 'Str0ngP@ss!',
            'full_name': 'Test Author',
            'email': 'test@example.com',
            'academic_degree': 't.f.n.',
            'affiliation': 'Onkologiya markazi',
            'orcid_id': '0000-0000-0000-0001',
        })
        self.assertEqual(r.status_code, 302)
        self.assertTrue(User.objects.filter(username='testauthor').exists())
        author = Author.objects.filter(user__username='testauthor').first()
        self.assertIsNotNone(author)
        self.assertEqual(author.full_name, 'Test Author')
        self.assertEqual(author.email, 'test@example.com')
        self.assertEqual(author.academic_degree, 't.f.n.')
        self.assertEqual(author.affiliation_uz, 'Onkologiya markazi')
        self.assertEqual(author.orcid_id, '0000-0000-0000-0001')

    def test_register_rejects_duplicate_username(self):
        User.objects.create_user('existing', password='Str0ngP@ss!')
        r = self.client.post(reverse('journal:register'), {
            'username': 'existing',
            'password1': 'Str0ngP@ss!',
            'password2': 'Str0ngP@ss!',
            'full_name': 'Test',
            'email': 'new@example.com',
            'affiliation': 'Test',
        })
        self.assertEqual(r.status_code, 200)

    def test_register_rejects_mismatched_passwords(self):
        r = self.client.post(reverse('journal:register'), {
            'username': 'newuser',
            'password1': 'Str0ngP@ss!',
            'password2': 'DifferentP@ss!',
            'full_name': 'Test',
            'email': 'new@example.com',
            'affiliation': 'Test',
        })
        self.assertEqual(r.status_code, 200)

    def test_login_page_renders(self):
        self.assertEqual(self.client.get(reverse('journal:login')).status_code, 200)

    def test_logout_redirects(self):
        user = User.objects.create_user('testuser', password='Str0ngP@ss!')
        self.client.login(username='testuser', password='Str0ngP@ss!')
        r = self.client.post(reverse('journal:logout'))
        self.assertEqual(r.status_code, 302)

    def test_submit_article_requires_login(self):
        r = self.client.get(reverse('journal:submit_article'))
        self.assertEqual(r.status_code, 302)
        self.assertIn('/kirish/', r.url)

    def test_submit_article_creates_draft(self):
        user = User.objects.create_user('author1', password='Str0ngP@ss!')
        self.client.login(username='author1', password='Str0ngP@ss!')
        pdf = SimpleUploadedFile('test.pdf', b'%PDF-1.4 test', content_type='application/pdf')
        r = self.client.post(reverse('journal:submit_article'), {
            'title_uz': 'Yangi maqola',
            'title_en': 'New Article',
            'abstract_uz': 'Annotatsiya matni',
            'article_type': 'research',
            'category': self.cat.pk,
            'keywords_text': 'saraton, immunoterapiya, kimyoterapiya',
            'issue_text': 'Vol. 5, No. 2, 2025',
            'doi': '10.1234/test.2025.001',
            'pdf_file': pdf,
        })
        self.assertEqual(r.status_code, 302)
        article = Article.objects.filter(submitted_by=user).first()
        self.assertIsNotNone(article)
        self.assertEqual(article.status, 'draft')
        self.assertEqual(article.title_uz, 'Yangi maqola')
        self.assertEqual(article.doi, '10.1234/test.2025.001')
        self.assertEqual(article.keywords.count(), 3)
        self.assertIsNotNone(article.issue)
        self.assertEqual(article.issue.volume, 5)
        self.assertEqual(article.issue.number, 2)
        self.assertEqual(article.issue.year, 2025)

    def test_my_articles_requires_login(self):
        r = self.client.get(reverse('journal:my_articles'))
        self.assertEqual(r.status_code, 302)
        self.assertIn('/kirish/', r.url)

    def test_my_articles_shows_only_own_articles(self):
        user1 = User.objects.create_user('user1', password='Str0ngP@ss!')
        user2 = User.objects.create_user('user2', password='Str0ngP@ss!')
        Article.objects.create(title_uz='A1', title_en='A1', submitted_by=user1)
        Article.objects.create(title_uz='A2', title_en='A2', submitted_by=user2)
        self.client.login(username='user1', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:my_articles'))
        self.assertEqual(r.status_code, 200)
        self.assertContains(r, 'A1')
        self.assertNotContains(r, 'A2')

    def test_edit_article_draft(self):
        user = User.objects.create_user('editor', password='Str0ngP@ss!')
        article = Article.objects.create(title_uz='Eski', title_en='Old', submitted_by=user, status='draft')
        self.client.login(username='editor', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:edit_article', args=[article.pk]))
        self.assertEqual(r.status_code, 200)

    def test_edit_article_published_forbidden(self):
        user = User.objects.create_user('editor2', password='Str0ngP@ss!')
        article = Article.objects.create(title_uz='Pub', title_en='Pub', submitted_by=user, status='published')
        self.client.login(username='editor2', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:edit_article', args=[article.pk]))
        self.assertEqual(r.status_code, 302)

    def test_edit_article_other_user_forbidden(self):
        user1 = User.objects.create_user('owner', password='Str0ngP@ss!')
        user2 = User.objects.create_user('hacker', password='Str0ngP@ss!')
        article = Article.objects.create(title_uz='Mine', title_en='Mine', submitted_by=user1, status='draft')
        self.client.login(username='hacker', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:edit_article', args=[article.pk]))
        self.assertEqual(r.status_code, 404)

    def test_rejected_article_shows_reason(self):
        user = User.objects.create_user('rejected_user', password='Str0ngP@ss!')
        Article.objects.create(
            title_uz='Rad', title_en='Rej', submitted_by=user,
            status='rejected', rejection_reason='Format mos kelmadi',
        )
        self.client.login(username='rejected_user', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:my_articles'))
        self.assertContains(r, 'Rad etilgan')
        self.assertContains(r, 'Format mos kelmadi')

    def test_edit_rejected_resets_to_draft(self):
        user = User.objects.create_user('resub', password='Str0ngP@ss!')
        article = Article.objects.create(
            title_uz='Resubmit', title_en='Resubmit', submitted_by=user,
            status='rejected', rejection_reason='Bad format',
        )
        self.client.login(username='resub', password='Str0ngP@ss!')
        pdf = SimpleUploadedFile('test.pdf', b'%PDF-1.4 test', content_type='application/pdf')
        r = self.client.post(reverse('journal:edit_article', args=[article.pk]), {
            'title_uz': 'Resubmit Updated',
            'abstract_uz': 'Updated abstract',
            'article_type': 'research',
            'category': self.cat.pk,
            'pdf_file': pdf,
        })
        self.assertEqual(r.status_code, 302)
        article.refresh_from_db()
        self.assertEqual(article.status, 'draft')
        self.assertEqual(article.rejection_reason, '')

    def test_edit_profile_requires_login(self):
        r = self.client.get(reverse('journal:edit_profile'))
        self.assertEqual(r.status_code, 302)
        self.assertIn('/kirish/', r.url)

    def test_edit_profile_updates_author(self):
        from journal.models import Author
        user = User.objects.create_user('profileuser', password='Str0ngP@ss!')
        Author.objects.create(user=user, full_name='Old Name')
        self.client.login(username='profileuser', password='Str0ngP@ss!')
        r = self.client.post(reverse('journal:edit_profile'), {
            'full_name': 'New Name',
            'academic_degree': 't.f.d.',
            'affiliation_uz': 'Test kafedra',
            'orcid_id': '0000-0000-0000-0000',
            'email': 'test@example.com',
        })
        self.assertEqual(r.status_code, 302)
        author = Author.objects.get(user=user)
        self.assertEqual(author.full_name, 'New Name')
        self.assertEqual(author.academic_degree, 't.f.d.')

    def test_submit_with_co_authors(self):
        from journal.models import Author
        user = User.objects.create_user('coauthor', password='Str0ngP@ss!')
        Author.objects.create(user=user, full_name='Main Author')
        self.client.login(username='coauthor', password='Str0ngP@ss!')
        pdf = SimpleUploadedFile('test.pdf', b'%PDF-1.4 test', content_type='application/pdf')
        r = self.client.post(reverse('journal:submit_article'), {
            'title_uz': 'Ko\'p mualliflik maqola',
            'abstract_uz': 'Test',
            'article_type': 'research',
            'category': self.cat.pk,
            'co_authors': 'Aliyev Vali\nKarimova Saoda',
            'pdf_file': pdf,
        })
        self.assertEqual(r.status_code, 302)
        article = Article.objects.filter(submitted_by=user).first()
        self.assertIsNotNone(article)
        self.assertEqual(article.authors.count(), 3)

    def test_review_status_displayed(self):
        user = User.objects.create_user('reviewuser', password='Str0ngP@ss!')
        Article.objects.create(title_uz='Review', title_en='Rev', submitted_by=user, status='review')
        self.client.login(username='reviewuser', password='Str0ngP@ss!')
        r = self.client.get(reverse('journal:my_articles'))
        self.assertContains(r, 'Ko\'rib chiqilmoqda')
